version: "3.9"

services:
  litestar_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
